### ISSUE TITLE
cannot get video info

### ISSUE THREAD

**Issue by krizpy82** [thecoder75/liveme-tools#100]
Im having trouble with a lot of videos. this on in particular http://file.live.ksmobile.net/yolo-XXXXXXXXXXXXXXXXXXXX--XXXXXXXXXXXXXX.m3u8, will play right on chrome with my phone, but in the program it doesn't find any information at all either by url or videoid search. some others have worked, but a lot dont, eventhough the will play on the phone and download through an m3u8 converter.

**Comment by thecoder75** [comment]
Even though the playlist for a replay is still available for access on the server doesn't mean LiveMe still has the replay in their database which is what LiveMe Tools queries for information.

**Comment by buddythecow** [comment]
I tried to ask this in the discord, but the invite expired that you have posted on here. I know back in October the query for videoID's changed. I saw that zq provided an update, but I couldn't figure out how to query from a web browser. Is this still possible?
