### ISSUE TITLE
Downloader Enhancements

### ISSUE THREAD

**Issue by polydragon** [thecoder75/liveme-tools#101]
- [x] Concurrency
- [x] Download chunks individually, then combine after.
- [ ] If you lose internet connection even for a second while downloading a list, the downloader carries on but figures the files don't exist any more, and removes them from the queue.

To-do on new module:
- [x] Download queue manager. (Automatically start the next download once one is finished)
- [x] Emit events when needed
- [x] Combine chunk download percentage into a total percentage for that playlist.
- [x] Error handling (related to note above about internet connection)
- [x] Clean up chunks after merge
- [x] Save/load from JSON/database
- [x] Re-add variables to rename downloaded files

Progress is over at: https://github.com/polydragon/lmt-downloadmanager
When it's done I'll merge it over here and integrate it with the UI; it's easier to debug like this.

**Comment by thecoder75** [comment]
Default filename handling is broken as the myqcloud links cause it the name the files `playlist_eof.mp4` instead of using the previous long alphanumber mix for naming the files as was done previously.  Just found this during testing so not sure if it got overlooked.

Otherwise this is coming along nicely.

**Comment by thecoder75** [comment]
Not sure if you looked into getting around the need for using VPN to download some of the playlists yet or not also.

**Comment by thecoder75** [comment]
@polydragon I was able to fix the filenaming issue, line 94 of the `index.js` file for the Downloads module referenced `.TS` files and should reference `.MP4` files as you change the extension in the lines above.

**Comment by ushall** [comment]
just tested it on the 7.0 prerelease. It works like a charm on vod2 hosted file, which was sooo slow before. Will now continue exploring / testing the 7.0 new stuff.
well done guys, keep on the good work !

**Comment by thecoder75** [comment]
@ushall Have the downloads been completing on you?  What OS/specs are you running as others have reported some issues.

**Comment by polydragon** [comment]
Closed as development tracking done, bug tracking is in #107
