### ISSUE TITLE
Option to tag for download/tag all for download/clear all

### ISSUE THREAD

**Issue by thegeezer9999** [thecoder75/liveme-tools#103]
6.21: 
W10 x64: 
**Subsystem**:

**Comment by thecoder75** [comment]
Adding this type of feature really other than **Download All**, I see as no benefit as you can click on the downloads button for individual.  

The problem with adding the ability to **Download All** is the replay list is loaded dynamically on-demand and may cause some replays to not be downloaded.  

For this I have to classify this feature request not possible at this time but may be discussed and added in a future release.
