### ISSUE TITLE
Chat Download

### ISSUE THREAD

**Issue by mmind99** [thecoder75/liveme-tools#112]
Just a quick feature suggestion.  Might be nice to be able to download the chat text as a .txt file.  I would like to be able to click the video download button and then click a chat download button right beside it.  Have it save it as the same file name, only with a different file extension.  I'm all the time wishing I had the chat I could go back and reference the time stamp on.

**Comment by thecoder75** [comment]
I'm sorry, but no new features will be added at this time.

**Comment by mmind99** [comment]
Thanks for reopening this! I believe this will be really useful.

**Comment by thecoder75** [comment]
@polydragon added this to his app.  You can follow up on his Github page regarding this.
