### ISSUE TITLE
Viewing History Setting Doesn't Save

### ISSUE THREAD

**Issue by mmind99** [thecoder75/liveme-tools#113]
The View History setting will not change.  Currently I have it set on (Keep Visiting Profiles Marked Marked for: 1 Day).  Whenever I change that value to (3 days) and hit save, the window will go away.  However, when I go back into the preferences, the value is right back to (1 day).

Version: 7.0.1 and 7.0.2
Platform: Windows 7 and Windows 10

**Comment by mmind99** [comment]
Also, is there a limit on how many users can go shaded?  Seems to not be updating the shading as it should now.  I click on a user and browse their list, but they don't always get shaded as they should.

**Comment by thecoder75** [comment]
There is no limit other than the database/JSON storage file cannot exceed 200MB (Approx. 1 Million Profiles+)

If you've reached a limit it means a corrupt record was generated and stored and is causing additional entries to be added but not detected.  I'll look into this part.

An update will be pushed out for the first part of the issue which fixes the saving of the setting.

**Comment by mmind99** [comment]
Thanks!  Yea, it seems nothing is getting shaded anymore.  I'd say you are correct.

**Comment by mmind99** [comment]
Just verified on my end, 7.0.3 fixes the saving of the setting.  Thanks!

**Comment by thecoder75** [comment]
I'll close this and open a new ticket regarding the other issue for easier tracking.
