### ISSUE TITLE
Can't Remove Users From Favorites List

### ISSUE THREAD

**Issue by mmind99** [thecoder75/liveme-tools#114]
When a user is added to the favorites list, I am unable to remove them.  When you click on them, the "Favorite" button is highlighted white.  When you click the button again it will unhighlight as it should.  However, the user is never removed from the list.  When you click on the user again later, it is right back to having the "Favorite" button highlighted.

Version: 7.0.2
Platform: Windows 7

**Comment by thecoder75** [comment]
After you removed the user from your Favorites, did you refresh your Favorites list or close and re-open the Favorites window to verify they were still there or gone?  Knowing will help to track down the bug.

**Comment by mmind99** [comment]
Neither one seems to work.  Closing and opening is usually how I do it.  But I just now tried the refresh button and it gets the same result, still not removing the user.

**Comment by mmind99** [comment]
And just for the record...the fav list probably only has 40 or 50 on it.

**Comment by thecoder75** [comment]
It sounds like the database json file might have gotten corrupt and is causing you all sort of issues.

**Comment by mmind99** [comment]
You know, now that I think about it.  I believe this may have started after I tried out the import / export of the favs.  Just don't know for sure because I went a while before trying to remove someone.  Anyway I can blow that database out and start from scratch?  I can add them back in manually.

**Comment by thecoder75** [comment]
Yes, if you go into the folder which the data files for the app, there should be a file called `livemetools_db.json` that you can remove and it'll force the app to rebuild it with converting your old favorites over to it.

**Comment by mmind99** [comment]
Well thats odd.  That removed about half of them.  Probably 20 or so remained.  Still didn't fix the removal issue either.  Think my install may just be hosed.  I don't care to start from scratch.  I just hate to loose the green bars that tell me what has been downloaded.  The rest I don't care about.  Could I restore just that or is that embedded with a bunch of other stuff?

**Comment by thecoder75** [comment]
What you've downloaded is stored in the downloadHistory.json file.  If you back that up and wipe all the other files and put that back the app will remember what you've downloaded.

**Comment by mmind99** [comment]
Cool.  I've still go something crazy going on.  I renamed the LiveMeTools folder to LiveMeTools.old and did a fresh install.  7.0.x will not install at all.  I just closes everytime saying it stopped working.  6.3 would work and build a new folder.  Not sure what thats all about.  But even after building a new folder with 6.3, then going to 7.0.x, it still closes.  I put my old LiveMeTools folder back in and 7.0.3 works perfect.  I'll keep digging, may be tomorrow.   Appreciate the help.

**Comment by thecoder75** [comment]
There's a major bug in 7.0.x releases right now related to the downloader that's causing it to fail on fresh installs.  I'm hoping to hear from @polydragon soon on it.

**Comment by mmind99** [comment]
Ah ok.  Thanks for the heads up.  I tried everything.  New folders, new ffmpeg installs, etc.  I'll just hang out on my old install for now.  No big deal.

**Comment by thecoder75** [comment]
The 7.0.x release are still marked pre-releases right now due to the issues that keep popping up.  As soon as they are all cleared then it'll be classified a stable release instead.

**Comment by mmind99** [comment]
Sounds good.  I'll try to help where I can.

**Comment by thecoder75** [comment]
I found the favorites bug and have applied the fix to the code and will be pushing the update out to the 7.0.5 release.
