### ISSUE TITLE
Converting Favorites, please wait...

### ISSUE THREAD

**Issue by mmind99** [thecoder75/liveme-tools#117]
When running the 7.0.4 pre-release, the application hangs at "Converting Favorites, please wait..."  It will remain there with only the queue window available.  The only solution I can find is to start the Task Manager and end "Update Status".  This will resume normal operation, but I'm guessing the favorites list didn't get what it needed.  It will do this on subsequent starts as well.

Version: 7.0.4
Platform: Windows 7 Ultimate

**Comment by thecoder75** [comment]
Fix will be pushed to 7.0.5 release.

**Comment by mmind99** [comment]
I still see the message in 7.0.5

**Comment by mmind99** [comment]
Thanks...7.0.6 fixed it!
