### ISSUE TITLE
Javascript Error in 7.0.5

### ISSUE THREAD

**Issue by mmind99** [thecoder75/liveme-tools#118]
This is what I get when trying to start 7.0.5 in Win 7.  Never gets beyond this.

![untitled](https://user-images.githubusercontent.com/33794328/33195432-65925eb8-d0a5-11e7-91a7-dac8aed53e29.png)

**Comment by thecoder75** [comment]
I'm triggering a new build now as I believe there was a glitch during the build process.  It should be ready for downloading again shortly.

**Comment by mmind99** [comment]
That fixed the JavaScript error.  Still see the Converting Favorites issue though.
