### ISSUE TITLE
Progress bar doesn't show anything.

### ISSUE THREAD

**Issue by tp9iner** [thecoder75/liveme-tools#121]
Works fine on one computer, but it's like blank on my other one. How do I fix this? Do I need to reinstall .net framework or something similar?

**Comment by polydragon** [comment]
This is usually caused by not having ffprobe set up correctly in the settings.

**Comment by tp9iner** [comment]
I definitely set the path correctly in the settings. I went into the roaming folder and deleted both settings and preferences file (why is there two?) One of them had a date modified of over 1 month ago, even though I opened the program today. It worked fine afterwards, but then I closed the program and opened it, and the progress bar window was bugged out again.

Also, I noticed there are two different download queue files: one is downloadQueue.json and the other download-queue-v2.json. Not sure if that is a problem.

**Comment by tp9iner** [comment]
I did not want to close this, is it closed?

**Comment by tp9iner** [comment]
It still is happening. It works fine after deleting the preferences file, but it seems most of the time, the next time I open the program it happens again. The download queue window will look very bugged. I double check the path, and it is correctly set.

**Comment by thecoder75** [comment]
Make sure you don't have any antivirus or gatekeeper software running causing access issues to `ffprobe` command.  Have you tried copying `ffmpeg` and `ffprobe` to `C:\Windows` directory?

**Comment by tp9iner** [comment]
I don't run any antivirus at all.

Screenshot: https://imgur.com/a/2gacd

That's an example of what the queue window looks like a lot of the time. I just opened the program and notice how the main window looks and missing the search bar. Occasionally the main window is glitched up, I simply reopen the program and it fixes itself. The download queue, however, as I've said already, doesn't fix until I delete the preferences file.

Really strange.

**Comment by thecoder75** [comment]
This is definitely strange.  Unfortunately it looks like an issue that I can't resolve as to have that kind of stuff happen could be caused by either a conflict with software installed on your computer, driver issues with video card, or some other issue that is more specific to you and not everyone as no one else has ever reported anything similar.
