### ISSUE TITLE
Empty See all List and no Replay Broadcasts

### ISSUE THREAD

**Issue by SteveKajak** [thecoder75/liveme-tools#125]
in all Versions of Livemetools 
Platform: Windows 10

Hi, today i missed from my Favorite Broadcasters the List of Replays and by Omg Live Broadcasters the See all List. Its now empty ? Why ?  help me please thank you !

**Comment by tp9ine** [comment]
Can confirm. It is completely broken! :(

**Comment by zeno12333** [comment]
yea same peoblem, is thecoder even still around ?

**Comment by SteveKajak** [comment]
Apparently, since today, credentials have become mandatory. This is also the case with the new Liveme Pro Tool. I hope that can be solved.

**Comment by zeno12333** [comment]
hopefully its easy fix

**Comment by tp9ine** [comment]
> Apparently, since today, credentials have become mandatory. This is also the case with the new Liveme Pro Tool. I hope that can be solved.

what does that mean. they're trying to block ppl from downloading?

**Comment by jonty123456** [comment]
can anybody get it to wok again

**Comment by jonty123456** [comment]
work

**Comment by SteveKajak** [comment]
only the codiers

**Comment by thecoder75** [comment]
The [LiveMe-API](https://github.com/thecoder75/liveme-api/) module has been updated to support the new changes.

However, I'm stepping down on active development of the various tools projects, someone else will have to step up and add the necessary interfaces and updates for things to continue working.
