### ISSUE TITLE
Downloader enhancements

### ISSUE THREAD

**Issue by polydragon** [thecoder75/liveme-tools#16]
~~#15 needs to be completed first.~~

Redo parts of the downloader to send along the username, user ID and video title (if set) with the URL to download, allowing to add them as variables to the download path.

- [x] Add `%username%` variable to parse from the download path setting, replacing it with the users username.
- [x] Add `%userid%` variable to parse from the download path setting, replacing it with the users id.
- [x] Add `%videotitle%` variable to parse from the download path setting, replacing it with the videos title, or `(no title)` if none set.
- [x] Add `%videoid%` variable to parse from the download path setting, replacing it with the videos id.
- [x] Add `%videotime%` variable to parse from the download path setting, replacing it with the videos start time.

- [x] Support for pausing & resuming downloads.
- [x] Ability to remove an entry from the queue list.

**Comment by thecoder75** [comment]
I will lay out the Settings page and code to add a spot where this can be defined.  Should we add the ability to browser for a folder for the download location or just leave it as an input field?

**Comment by polydragon** [comment]
I'm not sure. A browse window would be better for user experience but then you can't really add in the variables because it won't exist, so a text box would be better for the variables.

Unless we have it so you select a main download directory, then have a separate text field for a filename, where you can also define subfolders.

You would end up with something similar to this:

Download Path: `/media/downloads/liveme`
Filename: `%userid% - %username%/[%videotime%] $videotitle% (%videoid%)`

Which would then resolve to something like this behind the scenes:

`/media/downloads/liveme/123123123 - MyName/[2017-08-11 00:00] My Super Awesome Live (123123).ts`

**Comment by thecoder75** [comment]
I was thinking of a section where it says file naming with a drop down, choices:  Use playlist filename or custom filename.  If they choose custom, a second textbox would become visible allowing them to enter the variables.  

The main download path textfield would also be editable text, the browser for location would help them in getting started was the thought I had.

**Comment by polydragon** [comment]
Right, okay. Thought you meant replacing the textbox, so your idea will work out perfect.

**Comment by thecoder75** [comment]
How would or should we handle when its set to custom file name and the custom scheme results in a null or blank filename?  Should we default back to using the playlist name or something?  Just a thought.

**Comment by thecoder75** [comment]
And actually if we did it correctly for the folder browsing option, most OSes have an option to create a folder from that dialog which would also work for download location selection.  Then we wouldn't have to worry about creating folders.  Unless we want to provide an option to group videos in folders based on user id.

**Comment by polydragon** [comment]
If somehow the entire filename is empty/null then yes, setting it back to the playlist name would be the safest option.

Yeah, the OS will allow you to create a folder from that dialog, but then you can't auto-generate one per user.
Then, if you add an option to 'auto generate by user ID' so you would have things like `12312312\video.ts`, what if the user wanted `12312312 Username\video.ts`? You would also have to add an option for that, as well.

The easiest option would be to have the folder selection dialog for the main folder, with the default option being saving as playlist name. Then the downloader would work exactly identical to the way it does now.

But if the user chooses the custom option, then the user could change it how they would like it to be, adding subdirectories wherever they want by just adding a directory seperator, and using the variables to get it named exactly how they like it. Creating subdirectories in node is simple so it's nothing we need to worry about.

**Comment by thecoder75** [comment]
Need to add ability to also manually remove an entry from the queue list.

**Comment by polydragon** [comment]
Adding todo list here so I don't forget it:

- [ ] Add remove button for individual downloads. Send an event to the downloader to the already existing function.
- [ ] Add a global pause/resume button to main window.
- [ ] Add ability to use path separator characters in the filename template, creating directories as needed. (update getLocalFilename(x) to check base directory and recursively create subdirectories)
