### ISSUE TITLE
Documentation needed?

### ISSUE THREAD

**Issue by thecoder75** [thecoder75/liveme-tools#17]
Should documentation be written up on how to use this for newbies and how to use it as a power user?

**Comment by polydragon** [comment]
Documentation is always useful, though it doesn't have to be a priority.

**Comment by thecoder75** [comment]
Yes this is a low priority, but just wanted to throw it out there.

**Comment by thecoder75** [comment]
Closing this for now, maybe in the future we can use the Wiki function for documentation or a quick Q&A list for newbies to read.
