### ISSUE TITLE
Rewrite Settings & Favourites etc.?

### ISSUE THREAD

**Issue by polydragon** [thecoder75/liveme-tools#18]
For improved reliability of saving & loading data, we can use something like [electron-settings](https://www.npmjs.com/package/electron-settings).

This way, settings, favourites etc will only get saved when and if they change, and only get loaded once on app startup, removing unnecessary I/O operations, in addition to simplifying a _lot_ of _repeated_ code, meaning less bugs.

If you think this is a good idea, I'll make a new branch for it, as it is something that is vital to the whole system functioning correctly we wouldn't want to push out a new version with obvious bugs. Then I'll merge it back in when it's complete.

**Comment by thecoder75** [comment]
Yes and no, on settings I'd say yes, we can use that instead.

But for Favorites, it may not work for it.  Favorites is a database that has to be changed and the changes have to be written or read in real-time to avoid any issues.  If anything right now, the Favorites window needs to have a way of knowing when the list changes and needs to be reloaded.

Maybe moving the Favorites code to the main index.js file and writing up responders to handle data passing back and forth may be the solution.  This way if a write request is issued, it can also tell the Favorites window that it needs to refresh its list.

Yes, lets start a new branch.  Maybe call the branch 4.x.x as I would like to clean up the UI a bit too and this way we can continue any bug fixes on the current 3.x.x branch and just implement new features and improvements in the 4.x.x branch.

**Comment by polydragon** [comment]
I don't really see where this real-time stuff comes in with your current code for favourites. You're constantly reading and saving the file every single time you want to make a change or check if someone is favourited.

Moving the favourites code to a central location is the best idea. Store the favourites as one list in a variable, that's loaded when the app loads, and saved whenever it gets added to or removed from. You won't need to load the file again because it will already be up-to-date. The functions for adding/removing favourites can then signal the favourites window to update using the variable we already have.

I'll make a 4.0.0 branch and a 4.0.0 milestone and tag things correctly to keep track of this.

**Comment by thecoder75** [comment]
Originally I had some weird issues involving the favorites but I think they're all gone now anyways so we can begin moving the code around and cleaning up things.

**Comment by thecoder75** [comment]
I'm going to begin working on rewriting the favorites storage and retrieval functions.

**Comment by thecoder75** [comment]
Settings and Favorites both have been rewritten now improving their performance and more.
