### ISSUE TITLE
Change Video Player

### ISSUE THREAD

**Issue by thecoder75** [thecoder75/liveme-tools#19]
Right now it uses the HLS.js video player.  Should we look into using external or adding option for using an external player?

**Comment by polydragon** [comment]
I don't see a reason to change it. Most people (should) have been using the native-hls extension for Chrome or Firefox when using other (worse) tools to view videos. That extension also uses the HLS.js video player and I see no reason to swap it out for anything else. It works perfectly and it's fully included within the app. From my experience, external programs like VLC or something do not work as well.

**Comment by thecoder75** [comment]
Okay, just wanted to get your input on it.  Since HLS.js is the best solution right now I'm going to close this ticket.  If in the future something new and better comes out then we can revisit the topic.
