### ISSUE TITLE
Figure out a good Settings naming scheme

### ISSUE THREAD

**Issue by thecoder75** [thecoder75/liveme-tools#20]
Thinking like:

```downloads.directory``` Download location
```downloads.filemode``` Filenaming mode
```downloads.history``` Whether to remember what's been downloaded
```downloads.concurrent``` Simultaneous downloads (???)

**Comment by polydragon** [comment]
Looks good to me.

**Comment by thecoder75** [comment]
What are the defaults for these settings, I attempted to do a test download and it error'd out on me.
