### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by OnKneesForJesus** [thecoder75/liveme-tools#28]
While attempting to download a video, sometimes you will get an endless supply of Javascript Errors.

Uncaught Exception:
TypeError: Cannot read property 'isVisible' of null

**Comment by thecoder75** [comment]
Only place I'm seeing an isVisible check is in the main index.js file and that's when a download-add command is issued.  Not sure why this error would even ever occur.

**Comment by thecoder75** [comment]
@OnKneesForJesus Need more details to reproduce this error (UserID and Video URL would be helpful.)

**Comment by thecoder75** [comment]
I've added an error handler for now as I don't understand how this error could occur as to the structure of the code.  Will close and commit patch and build.
