### ISSUE TITLE
Occasional Download Stall

### ISSUE THREAD

**Issue by thecoder75** [thecoder75/liveme-tools#30]
Every once in awhile queue will show an active download that stalls, no errors are thrown and no indications to why either.

Can only quit and restart app to get queue to start up again.

**Comment by thecoder75** [comment]
I've not seen this again, only 3 times out of 50 runnings so far and always different URLs.

**Comment by thecoder75** [comment]
It seems to happen more with the m3u8stream downloader than with FFMPEG downloader.

**Comment by polydragon** [comment]
I've been going over the code and can't figure out why this would happen. Maybe it's something to do with the m3u8stream downloader having issues with certain files. It could have downloaded a chunk, then the processing afterwards throws an error, but it doesn't trigger the errored event.

I've only been using the ffmpeg downloader and haven't noticed any issues like this with that one.

**Comment by thecoder75** [comment]
Yeah me too.  I also find the ffmpeg downloader tends to download faster too most of the time compared to m3u8stream.

**Comment by thecoder75** [comment]
For some reason lately during testing the FFMPEG downloader keeps erroring out on me while the m3u8stream downloader works fine.  Still have to quit and restart app when the downloader hangs though.  I've had it happen mainly when I have a large queue built up too if this helps.

**Comment by thecoder75** [comment]
I've had this happen now too with the FFMPEG downloader a couple times, think its more related to the LiveMe servers doing it than the downloaders.
