### ISSUE TITLE
clear download queue

### ISSUE THREAD

**Issue by starsaillor** [thecoder75/liveme-tools#32]
Hello, 

How can one clear the download list? I have many links that seem to be stuck and won't download, I restarted but the list continues...

**Comment by thecoder75** [comment]
At this time the only way to clear it is to quit the app, go to the AppData folder where all the data files are stored and remove the download_queue.json file.  

I will push this through as a feature request for the next version too.

**Comment by starsaillor** [comment]
it worked, thanks a lot, keep up the good work!

**Comment by thecoder75** [comment]
You're welcome.  Hopefully we'll be able to add a force-flush for the queue to the app somewhere.

**Comment by thecoder75** [comment]
Added force flush of download queue to settings page that will tell the app to wipe the download queue in the event of a hang.
