### ISSUE TITLE
Uncaught exception when adding a favorite

### ISSUE THREAD

**Issue by slyfox99** [thecoder75/liveme-tools#34]
TypeError: Cannot read property 'send' of null
    at EventEmitter.ipcMain.on index.js:156:17

Reproduce:
Click the favorite heart and an exception window pops up. 
Favorites still get added/removed though

**Comment by thecoder75** [comment]
What version are you running?  This bug was recently addressed per Issue #31.

**Comment by thecoder75** [comment]
Issue has been duplicated in latest release and patched per this [commit](https://github.com/thecoder75/liveme-tools/commit/3b3508010dcb055b299f5d4c525e33a049d82b78)
