### ISSUE TITLE
API Finds

### ISSUE THREAD

**Issue by polydragon** [thecoder75/liveme-tools#38]
Seems Live.me has a website version too now, in addition to the app. Allows us to figure out more URLs to use to find people/videos easier using a web browser's developer tools.

It seems users can tag their videos with hashtags. I've figured out how to find the trending tags and search by hashtag. (I've never actually used the app, so I'm not sure what features it has)

## Get trending tags

This returns a list of trending tags.

`live.ksmobile.net/search/getTags`

Returns:

``{
   "status":"200",
   "msg":"",
   "data":[
      {
         "tag_name":"#RollYourTongue",
         "tag_id":""
      },
      {
         "tag_name":"#Singing",
         "tag_id":""
      },
      {
         "tag_name":"#Dancing",
         "tag_id":""
      },
      {
         "tag_name":"#Makeup",
         "tag_id":""
      },
      {
         "tag_name":"#Comedy",
         "tag_id":""
      },
      {
         "tag_name":"#Talk",
         "tag_id":""
      },
      {
         "tag_name":"#Art",
         "tag_id":""
      },
      {
         "tag_name":"#Food",
         "tag_id":""
      },
      {
         "tag_name":"#Games",
         "tag_id":""
      },
      {
         "tag_name":"#Sports",
         "tag_id":""
      }
   ]
}``

## Search by hashtag

The `search/searchKeyword` seems to have a `type` parameter too. When set to `2` it changes to the hashtag search mode. Use the keyword parameter as before, but put in the hashtag without the hash.

The `type` parameter defaults to `1` which is username search mode. Setting it to anything higher than `2` just returns empty data.

The URLs are constructed like so: `live.ksmobile.net/search/searchKeyword?type=2&page=1&keyword=Singing`

*Have not found any other use for this other than what was documented here.  Wish we could use it for other searches too!*

## Search for girls

`live.ksmobile.net/live/girls?page_index=1&page_size=20`

## Search for boys

`live.ksmobile.net/live/boys?page_index=1&page_size=20`

## Filter by country

`live.ksmobile.net/live/newMainInfo?countryCode=JP&page_index=1&page_size=20`

It seems the `countryCode=<code>` parameter seems to work on any URL. Searching for hashtag, name, or boys/girls.

## "Short"

Seems to be short videos.

`live.ksmobile.net/video/index?page=1&pagesize=20&page_index=1&page_size=20&pageSize=20`

I have no idea why page & page_index are both there, or pagesize, page_size & pageSize. I haven't played around with it to see what is required or not. `countryCode` does work.

## New streams

`live.ksmobile.net/live/homepageNew?page_index=1`

**Comment by thecoder75** [comment]
Most of these searches are related to live feeds, not past feeds.  While useful they are, they would be better suited for the LiveMeOMG project more than this one.

I'm not sure about the hashtag one being useful, doing a test I didn't find any videos really using them yet.  We can still implement this feature in case it picks up popularity in the future.

Thank you for finding these and figuring them out.

**Comment by thecoder75** [comment]
Maybe add hashtag search function to the app?

**Comment by polydragon** [comment]
Closing this due to the only relevant URL has already been implemented in the 5.x branch. Will move other URLs over to LiveMeOMG if/when that project is being worked on.
