### ISSUE TITLE
I really wish find some User-information starting from a playlist_eof.m3u8 link

### ISSUE THREAD

**Issue by hubslave** [thecoder75/liveme-tools#41]
I really wish fin some User-information starting from a playlist_eof.m3u8 link

**Comment by hubslave** [comment]
I really wish fin some User-information starting from a playlist_eof.m3u8 link

**Comment by thecoder75** [comment]
I'm sorry, but due to the encrypted style URL and the lack of documentation from LiveMe, doing a search based on this is impossible.
