### ISSUE TITLE
Downloads not working on macOS

### ISSUE THREAD

**Issue by Reck1501** [thecoder75/liveme-tools#42]
Downloads will not start on the macOS version. I can add them to the queue just fine, but they do not start downloading.

**Comment by thecoder75** [comment]
What version of macOS are you running under?  Are you using the internal or FFMPEG downloader in the Settings?  If FFMPEG is chosen, do you have FFMPEG installed in a folder in your path?  

I'm asking these questions as I run the macOS version and so do many others who test and report back and no one else has reported any problems downloading.

**Comment by Reck1501** [comment]
I've tried using both the internal and the ffmpegdownloader, and ffmpeg is in my path.

**Comment by thecoder75** [comment]
Have you tried using an older release to verify if it quit working recently?  Are you trying to run over a VPN or regular internet connection?  

I've still not found any ways the app would not begin downloads at this time.

**Comment by thecoder75** [comment]
The only time I can get downloads to stall or not work is by having active downloads running and connecting or disconnecting a VPN connection.  Other than this, I've not been able to reproduce the problem and have decided to close this ticket as the problem may be a third-party application or firewall interfering with the app on your computer.
