### ISSUE TITLE
Download stall after 20 videos?

### ISSUE THREAD

**Issue by thecoder75** [thecoder75/liveme-tools#44]
Saw a comment about someone saying they had 20 videos in the queue to download and it stalled.  Are there errors in the modules we're using causing this?

I've noticed too at times stalls happening now more frequent than before.

**See Issue #30 for past notes and discussions too.**

**Comment by thecoder75** [comment]
See if you can figure out why this happens at times please.

**Comment by polydragon** [comment]
I've gone over the code and had a bunch of completely random videos downloading for a few hours now and I haven't had any stall or anything like that. I'm really not sure what can be causing this. I've tried very long videos and shorter videos but none have stalled. I'll keep investigating.

**Comment by thecoder75** [comment]
Considering this a fluke and unable to produce same results as previously reported.
