### ISSUE TITLE
[Branch 5.0.0] Downloader

### ISSUE THREAD

**Issue by polydragon** [thecoder75/liveme-tools#47]
- [x] Adding a URL does not respect the downloader being paused (because a seperate `Downloads` module instance is being used here).
- [x] Empty queue button doesn't work (because a seperate `Downloads` module instance is used here).
- [x] Critical: ~Two~ Three `Downloads` modules are being used simultaneously. One in the `queue` window and another in the `main` window, and another in the `settings` window.
- [x] Critical: FFMPEG downloader will fail silently and empty the queue with failures, if FFMPEG is not found.
- [x] Removing a URL will sometimes remove the wrong one - causing it to "disappear" from the list but still retain its place in the queue.

4 out of 5 issues are caused by multiple module instances being used, instead of sending all requests to the same instance.

**Comment by thecoder75** [comment]
Each page is running inside its own renderer isolating it from the others which is why they need to run their own instance of the modules.  If it was critical, then we wouldn't have to use the IPC bridge all over the place.

**Comment by thecoder75** [comment]
Should we move these modules to the main thread and use IPC bridges for communications to avoid the multiple instance issue?

**Comment by polydragon** [comment]
But they shouldn't be running their own instance of the module. They should be using one instance. Either by sending it through the ipcRenderer to ipcMain, who then passes it on to the ipcRenderer of the main window to handle it - like it did in 4.0.0. The second option is to move it into the main process and either use ipcRenderer to send it to the main process that then passes it onto the module. A third option - though untested, is to use. require('electron'),remote.require('./modules/downloads') to grab the main process' instance of the module and use that directly. But that means rewriting parts of the module to remove all renderer related parts, and re-add them where they are needed in the  renderer process.

The simplest fix would be to remove the instances in the Queue and Settings windows, and pass those messages along to the Main window, which then gives it to the module, like it currently does for adding files to download/removing queued files/etc.

The best fix would be moving to the main process, but more work.

**Comment by thecoder75** [comment]
I'm in no hurry to release 5.0.0, rather have it solid and working then slightly buggy or breakable.  I'm up for working on moving everything to the main process and using IPC communications.
