### ISSUE TITLE
Overlooked API Functionality

### ISSUE THREAD

**Issue by polydragon** [thecoder75/liveme-tools#51]
There's things we overlooked when adding the new API calls:

- The `countryCode` URL parameter works with hashtag searches (not with username searches). A possible addition?
- Hashtag searches & username searches are paginated using the `page` URL parameter. Any reason we aren't showing more than one page?

I'm going to continue exploring the API and see what I can figure out of it.

**Comment by thecoder75** [comment]
I didn't think about the countryCode parameter.  

Every time I've tried doing a username search no matter what I do I can only get back 10 results.  I don't know if its what LiveMe has hard-coded or if its a different parameter that I don't know about.  When I tested I noticed the hashtag search also having the same issue.  Its why I commented in the code about it and have never figured out how to get past it.

**Comment by thecoder75** [comment]
Good idea, I was thinking of doing something similar but haven't gotten around to allocating a device to be a dummy tester.

Maybe the new module we're working on too might help overcome the search limitations.

**Comment by thecoder75** [comment]
I've been using Wireshark to watch what the app does and it looks like a lot of the communications is over SSL making it harder to crack.  I'm going to try and bypass using some tricks and a proxy server to see what I can come up with.

**Comment by thecoder75** [comment]
I'm closing this issue as it no longer pertains to the LiveMe Tools but rather moreso to the LiveMe API module.
