### ISSUE TITLE
Possible LiveMeOMG integration?

### ISSUE THREAD

**Issue by thecoder75** [thecoder75/liveme-tools#52]
Do you think people would like the ability to open a new window, see the current live broadcasts with user info and trigger searches on a user by clicking their ID or name?  

This would also allow us to add the rest of the **known** APIs to the tools and make it a better app for everyone to use.  

If we were to do this, would we want to actually create a *true* node module for the LiveMe API and move over to using it?  If we did this it would allow us to add new APIs as they are discovered and cracked to a more common platform that could then be integrated or used by more than one app or tool in the future.

**Comment by polydragon** [comment]
Yeah, I think something like that could be useful. If we merge the LiveMeOMG project with this one and create one tool that does everything a user could want when scanning liveme. Some people like to browse the live feeds and see what people are doing, recording them maybe. Others like browsing what people have already streamed and just simply download that. We can create a tool that does both.

A node module for the liveme api could be a good idea. It would standardize some of the complete mess that the api is, and if people wanted to develop their own tools they could. Though I doubt many people would. The benefits to us would be enough to justify it though, I think. I could add new parts to the api module without touching the actual front-end app, which means it shouldn't accidentally touch something else and break it.

We would need to actually plan it, or it wouldn't be any better than the live api currently is.

**Comment by thecoder75** [comment]
Its been added in the 6.0.0 release.
