### ISSUE TITLE
Empty Queue Issues

### ISSUE THREAD

**Issue by IceVmp** [thecoder75/liveme-tools#53]
As simple as the new empty queue button seems, it doesn't empty all the queue, it leaves the last archive to be on top (downloading one) there and it won't move away no matter what I do, not only it's glitched, now I can't take it away from there. 
Any help?
Note: Only way to fix this so far is to empty queue, close the app and reopen.

**Comment by polydragon** [comment]
There is currently no way to kill the 'active' download. It's something that I'm looking into for a future version.

**Comment by IceVmp** [comment]
Thank you very much, good luck and keep the hard work up!

**Comment by thecoder75** [comment]
The internal m3u8stream downloader module has a `.abort()` command that can be used with it.  We may have to find out on the FFMPEG module we use.  

Also I've noticed in testing that FFMPEG is not fully closed out of memory if you quit out too as I've had several stalled FFMPEG processes before during testing from quitting and restarting the app.  This is something we'll have to watch out for or find out if we can ensure its totally closed out if the app gets closed.
