### ISSUE TITLE
Versions 6.01/02 LMTools not exiting gracefully

### ISSUE THREAD

**Issue by thegeezer9999** [thecoder75/liveme-tools#64]
Also now getting this warning (maybe application did not properly close ?)
![image](https://user-images.githubusercontent.com/32274697/30846013-cf75068c-a28d-11e7-933b-0dba87b864f0.png)

Had to close 2 x LiveMe processes before could successfully re-launch LMTools

Regards

**Comment by thecoder75** [comment]
This issue has been resolved.
