### ISSUE TITLE
Version 6.01/02 FFMPEG missing warning on application startup

### ISSUE THREAD

**Issue by thegeezer9999** [thecoder75/liveme-tools#65]
Hi

Getting this warning msg on application startup. All seems to work after clicking OK EXCEPY LiveOMG video display - but this may not be related. Easy to click through so looks like a cosmetic cleanup issue ?

![image](https://user-images.githubusercontent.com/32274697/30846185-8647c390-a28e-11e7-8c37-dfb4fc3844fa.png)

**Comment by thecoder75** [comment]
The error message has been removed.
