### ISSUE TITLE
6.01/02 no right-click paste option

### ISSUE THREAD

**Issue by thegeezer9999** [thecoder75/liveme-tools#66]
Hi

Minor annoyance sonce you can still use the keyboard shortcuts, but the new version does not seem to allow right-click paste into the search bar. ried this on UserID and VideoID so guess this is the case for all.

**Comment by thecoder75** [comment]
The button attached to the UserID, VideoID and URL textfields will copy their contents to the clipboard saving you some clicking.

I will add the right-click menu back to the textfields as well.  Thought they were still there, sorry.

**Comment by thecoder75** [comment]
Added to the 6.0.3 release.
