### ISSUE TITLE
32-bit Builds

### ISSUE THREAD

**Issue by thecoder75** [thecoder75/liveme-tools#69]
Most linux distros are going 64-bit only now and macOS is 64-bit only.  Windows is the only one still offering 32-bit and 64-bit versions.  

The problem is that when I attempt to build 32-bit on the dev environment now it fails, but 64-bit builds just fine.  

Should we create 32-bit builds with new releases or phase out of 32-bit builds?

**Comment by polydragon** [comment]
With me building the Windows versions now, I'll build them. I agree that x86 is on the way out, but people do *still* use it for *some* reason, and I've had at least two people ask for a 32-bit version of 6.0.5 when there wasn't one previously.
