### ISSUE TITLE
macOS / FFMPEG detection issue

### ISSUE THREAD

**Issue by thecoder75** [thecoder75/liveme-tools#71]
When its ran in dev mode, it detects FFMPEG just fine.  When its built, detection fails.  May be related to macOS Filevault security or something, need to investigate more.

Are we going to need to add macOS specific detection code or something?

**Comment by polydragon** [comment]
Well, maybe. But I don't think this is anything I can help with any more, though. I don't have a system to test on and I don't know what sort of security or what could possibly be causing this.

**Comment by thecoder75** [comment]
This is a bug/issue that I have to figure out when I have time.  I'm hoping its not something that the Mac version has to be signed by a developer's certificate in order to get around things.

**Comment by thecoder75** [comment]
I'm lowering the priority on this fix down to low for now as new settings options added by @polydragon allow for a workaround fix to this issue right now.

**Comment by thecoder75** [comment]
Closing as no one else has reported the issue and with the new settings in place no problems are being experienced now with current builds.
