### ISSUE TITLE
Export Favorites list in V6.0.7 (file is not created)

### ISSUE THREAD

**Issue by amr18379** [thecoder75/liveme-tools#74]
Dear Thecoder75

Thanks for your response to fix the issue of the Favorites list in the previous version but currently there is no file created after exporting ,also how we can import that list to another PC?

**Comment by thecoder75** [comment]
The bug was found and fixed.  There will be a Favorites Import function in the next major release (6.1.0 possibly).  You can access the saved data location on your computer and copy the `favorites.json` file to the other computer for now.
