### ISSUE TITLE
user-friendly movie filenames

### ISSUE THREAD

**Issue by ushall** [thecoder75/liveme-tools#76]
LMT could include the username and the live datetime in filename while keeping some sort of unique identifier. 
A suggested format is `datetime.username.userid.videoid` such as `20171008233054.Princess_BadAss💙.914376685817137872.150791954118025717109.mp4`

Another option could propose to create per-user subdirectories

**Comment by thecoder75** [comment]
Have you checked in Settings?  There is an option to enable custom filenaming of the downloaded playlists, its been there since near the beginning.

**Comment by ushall** [comment]
oups, that's exactly what i was dreaming of . i must have been blinded by my Live.me favs lol
