### ISSUE TITLE
alternative for embedded player

### ISSUE THREAD

**Issue by ushall** [thecoder75/liveme-tools#77]
Did you guys checked the https://mpv.io player as an embedded player? 
It is very versatile and has some smart remote control possibilities. it is also based on ffmpeg and provide a bunch of options.

**Comment by thecoder75** [comment]
The player you're referencing is still in early development stages with no pre-built releases available for download.  Including/bundling it would offer no real benefit as we're already using HLS JS inside Electron which uses FFMPEG for video playback support.  

If you would like to suggest or inquire what additional controls we provide in the video window interface, we're open and willing to research the changes.

**Comment by MaxCaulfield95** [comment]
I think it would be handy to have the video length displayed next to the current time, and maybe a tooltip for easier seeking.

**Comment by thecoder75** [comment]
The length of the video is shown in the replay list but will see about updating the video player window interface to include the total length.

**Comment by thecoder75** [comment]
The player now supports showing the total video time as well as a better seek/position bar with a better buffer progress display.  

Any future requests for the player skin to be updated will need a new ticket open for those requests only to help track progresses better.
