### ISSUE TITLE
Error importing list of VideoIDs

### ISSUE THREAD

**Issue by thegeezer9999** [thecoder75/liveme-tools#78]
**Version**: 6.09
**Platform**: W10 x64
**Subsystem**: ?

**Comment by thecoder75** [comment]
What error do you receive or see when you attempt to import a list?  If you're importing a list of video ids that have been deleted, then nothing will be added to the queue for downloading.

**Comment by thecoder75** [comment]
This issue has been addressed and a fix will be included in the next release.
