### ISSUE TITLE
Deleted Video ID

### ISSUE THREAD

**Issue by amr18379** [thecoder75/liveme-tools#79]
Dear,

I noticed when you search by deleted video ID it will pop up with some details without m3u8 link so Maybe  we can get the deleted link  if you managed to refine the script .
 Check by Video ID : 15080344123497878247 .
Waiting your feedback ,Your effort is highly appreciated.

Best Regards

**Comment by thecoder75** [comment]
If no link is provided, it means that the video files themselves have been deleted on the server already and the database still holds some undeleted information on the video file.  

The next update will actually hide the Video URL and buttons if it detects it missing.
