### ISSUE TITLE
More than 10 broadcasts not appearing?

### ISSUE THREAD

**Issue by alansage** [thecoder75/liveme-tools#80]
**Version**: <6.0.10>
**Platform**: <Windows 10 x64>

When broadcaster has more than 10 broadcasts available, only the first ten appear to be visible.  Previous versions (5.x.x) were able to show all broadcasts

**Comment by thecoder75** [comment]
When you scroll to the very bottom of the list of replays, the app will fetch the next 10.  You **do** have to scroll to the very bottom of the replay list to get it to load more replays.

**Comment by alansage** [comment]
Sorry, it's just not doing it for me.  I can find a broadcaster with >10 broadcasts, and in 5.0.9 it scrolls just fine to the end, but in 6.0.10 it just stops on usually the 10th, but very occasionally the 20th.  Doesn't matter whether I drag the bar down, use the mouse wheel, cursor keys or what.  As an example user ID try 761862448348528640, this guy has nearly 500 broadcasts which I can see on 5.0.9 just fine, but only the first 10 on 5.0.10.   Sorry to be a pain but I don't know what I could be doing wrong and it's driving me mad!

**Comment by thecoder75** [comment]
In versions prior to 6, it loaded all the replays at once.  Starting with 6.0.0, the entire replay loader was rewritten from scratch to support smart scrolling without causing people to have to wait for data to load and render.

I did a search on that broadcaster ID and was able to go/scroll all the way back into July of this year without any problems (at least 250 entries loaded.)

As I cannot reproduce this in the test environments here I cannot classify this as a bug or an issue.  Are you sure you're not being blocked or throttled or have other internet related issues that might be causing data delays and timeouts?

**Comment by alansage** [comment]
I don't think so.  I've got a 250MB fibre connection and as I say, I can swap between new and old version at will; old works and new doesn't.  Is there any debug or anything I can forward you to help?

**Comment by thecoder75** [comment]
Sorry, nothing you can provide me with other what you already have.  Like I said before, I am unable to reproduce the issue on the test systems here.

**Comment by thecoder75** [comment]
I'm classifying this a dead topic as no one else has reported this issue at all on any OS platform and am guessing a 3rd party application or network security application to be the cause or issue behind the original poster's comments.
