### ISSUE TITLE
Global Search

### ISSUE THREAD

**Issue by amr18379** [thecoder75/liveme-tools#83]
Dear thecoder75,

Kindly I suggest to add search by Countrycode  as a global filter because there are many broadcasters are not shown due to lack of the global search.

Best Regards.

**Comment by thecoder75** [comment]
The `countryCode` option is available only for Username or Hastag searching.  Is this what you are referring to?  If so I will need to build a list of the different country codes in order to provide a dropdown selector when doing the searching.

**Comment by amr18379** [comment]
No need to build full list , you can set US as the default country code and allow the user to modify to search for his desired country such as ( GB,BR,JP,...etc.) .
You can use this URL :- 'https://live.ksmobile.net/live/newMainInfo?countryCode=US' in your code , or add search option (as a query) by country code such as the filter by global search in the App or the web portal without creating the drop down list.

**Comment by thecoder75** [comment]
The modification you're asking about is for the LiveMeOMG window of the app then and not the search?  Not everyone will know the country code for different countries so a list will need to be made and incorporated into the app.

**Comment by thecoder75** [comment]
I've compiled a Country Code list as a JSON file to include into the source tree which will allow this feature to be added in the next minor version release here soon.

**Comment by thecoder75** [comment]
LiveMe is not honoring the CC specified when doing a Username or Hashtag search or even any Live feed requests.  

Further research is now required to figure out why its not working when requesting filtered data from LiveMe even though their API URLs show the needed tags for support.

**Comment by amr18379** [comment]
Dear thecoder75,

Thanks for your response ,kindly check the attached link  ,Maybe it can help in the investigations.

The country Code : JP .

[src.zip](https://github.com/thecoder75/liveme-tools/files/1415002/src.zip)

**Comment by thecoder75** [comment]
Since this filtering does not work on **ALL** countries as tested, it's therefore deamed unreliable and many may see as a bug or an issue.  

For this reason alone **ONLY** the [LiveMe API](https://github.com/thecoder75/liveme-api/) has support for countryCode.  I will close this Issue Ticket as it cannot be implemented as a solid solution.
