### ISSUE TITLE
Save replay list.

### ISSUE THREAD

**Issue by justarandomhuman** [thecoder75/liveme-tools#90]
How about to have an option to save the replays of each user? 

When a user is suspended we cannot see their replays list anymore. So an option to save/autosave/reload playlists for each user would be awesome.
I'm thinking in this option like this:
 - In the main page, when the replaylist is shown, add a button so the user can add/remove the video to the saved list.
 - In favorites list: Add A checkbox in each user.
 - All users from favorites that have the autosave option checked, ping to the server at random minutes/seconds for each user, if new videos are found the new videos are added to the cached replays list.
 - A button in each user on the favorites list, if you click that button, the user is shown in the main window and the replay list is loaded from cache instead of load it from the liveme api.

Maybe there is a better and less complicated way to make this, but this is how I imagine this options.

Do you think that this feature could be added?

**Comment by thecoder75** [comment]
It's possible and will need to be thought about and researched more before it can be added.

**Comment by thecoder75** [comment]
Adding this feature would serve no purpose other than to add large data storage requirements to the app and possibly cause problems down the road with corrupt or lost data issues.  It's a feature/function that will not be added at this time but may be visited and discussed later in the future.
