### ISSUE TITLE
Issue with not being able to see > 10 broadcasts... think I've tracked it down

### ISSUE THREAD

**Issue by alansage** [thecoder75/liveme-tools#92]
I noted an issue a while ago about being unable to scroll beyond ten user's broadcasts.  You couldn't recreate the issue so understandably closed it.

Well, I've had to work out how to use nodejs and Electron and I think I've tracked it down.

The problem is in livemetools.js, in the $('main').scroll(function)

On my system the comparison 
if ($(this).scrollTop() + $(this).height() == $('.list').height())

never resolves as "true" - because the values are all decimal.  When scrolling down to the bottom of a list with > 10 broadcasts, the values on my system are:

(this)scrollTop =507.20001220703125
(this)height =773.6
(list)height =1281

result of addition =1280.8000122070312
...and so the comparison never seems to succeed.

I've resolved it by changing the comparison line to:

if ( Math.round( ($(this).scrollTop() + $(this).height()) ) == (Math.round ($('.list').height() )) )

and it seems to work a treat now.  

I'm absolutely not a javascript programmer though so can't vouch for the above being a valid fix, but hopefully it'll give you a pointer as to what was going wrong.

I'm really not sure why I experienced this problem and no-one else has reported it, but anyway - I've learned some new skills (I'd never even heard of Electron 2 weeks ago!) and hopefully helped out.

Thanks

**Comment by thecoder75** [comment]
I've updated the code a bit differently than what you did but it should work now more smoothly without any issues.  Instead of now waiting to scroll to the end to load more, it looks for the scroll position to be near the end to load more and help avoid this type of issue in the future.

Thank you for the research you did as the information provided allowed me to understand what was happening on your system and why and not happening to anyone else.

**Comment by thecoder75** [comment]
Just so you know, here's the updated code:

```javascript
	$('main').scroll(function() {
		if (($(this).scrollTop() + $(this).height()) > ($('.list').height() - 80)) {
			if (has_more == false) return;
			if (scroll_busy == true) return;

			current_page++;
			if (current_search == 'getUsersReplays') {
				getUsersReplays();
			} else if (current_search == 'performUsernameSearch') {
				performUsernameSearch();
			} else if (current_search == 'performHashtagSearch') {
				performHashtagSearch();
			}
		}
	});
```
