### ISSUE TITLE
Migrate from JSON files to lowDB

### ISSUE THREAD

**Issue by thecoder75** [thecoder75/liveme-tools#96]
Since some new features planned will require data storage of large sets and also due to the occasional favorites wipe glitch, I would like to move from using JSON file storage to NeDB for all database type data.

This will allow greater storage in the future with some limitations for now but will ensure 100% cross-platform ease at this time.

In a future release would like to consider either using special builds of SQLite or MonoDB or something similar that can be bundled with the app.

**Comment by johndenverisfullofshitman** [comment]
Is there any way of unscrambling the replays. Meaning that alot get stuck in a loop

**Comment by thecoder75** [comment]
Not sure what version this will be included in as some major rewriting needs to be done to the Favorites and Downloads custom modules.  May be better to create our own data management module that handles all stuff and the other modules use it to do the dirty work.

**Comment by thecoder75** [comment]
The migration has begun and preliminary testing is now showing that its actually faster using the lowDB module then it was originally working directly with the files.

All that is left is moving over the Import/Export Favorites code and adding support for storing and checking previously downloaded files.

@polydragon - Can you provide an event on completed download that I can tie to the DataManager module please.

**Comment by thecoder75** [comment]
All code related to Favorites has been moved over to new. 

So far testing has actually shown a major speed increase related to Favorites and also to handling/tracking visited profiles.  Tested with over 500 profiles viewed and logged and still saw no speed decrease or performance hit when loading Fans and Followings windows.

**Comment by thecoder75** [comment]
Migration is complete in 7.0.1 release.
