### ISSUE TITLE
Unable to search for usernames with emojis 

### ISSUE THREAD

**Issue by blackbart1** [thecoder75/liveme-tools#97]
**Version**: LiveMeTools-6.1.4
**Platform**: Mac

<

**Comment by thecoder75** [comment]
Please provide a couple example Usernames with Emojis so I can verify this issue.

**Comment by blackbart1** [comment]
Cheers that's great

**Comment by thecoder75** [comment]
This has been fixed in the custom API module and will be included in the next release.
