### ISSUE TITLE
Search Following/Followed by UID

### ISSUE THREAD

**Issue by thegeezer9999** [thecoder75/liveme-tools#99]
**Version**: 6.2.1
**Platform**: W10X64
**Subsystem**:

**Comment by thecoder75** [comment]
Can you please provide more details on what you're asking here, whether its a problem or a feature request?

**Comment by thegeezer9999** [comment]
Hi Coder/Polydragon
Search function within Following/Followers works fine for "Username Like" string, but if you search bu UID it does not work. Why you might need this is if you finished searching on a Username involving emojis, and wanted to resume from there, you cannot always work out which are the correct emojis, whereas a quick click on copy UID, allows you to save the UID. If you could then search the Following/Followers by UID, you could guarantee being able to resume your search. I hope that makes sense now ?

**Comment by thecoder75** [comment]
I've added it to the Fans and Followings windows along with displaying the User ID now and verified it to be working perfectly.

Expect this to be available in the next build release.
